### ISSUE TITLE
assets_manifest_backup: No such file or directory

### ISSUE THREAD

**Issue by jogaco** [capistrano-plugins/capistrano-faster-assets#4]
Whenever I peform a deploy, I get this error and all assets are precompiled, even if no changes to Gemfile or any of the assets:

```
INFO[435343cb] Running /usr/bin/env ls /home/deploy/project/releases/20141127132806/assets_manifest_backup on ip
DEBUG[435343cb] Command: cd /home/deploy/project/releases/20141127132806 && ( RAILS_ENV=production /usr/bin/env ls /home/deploy/project/releases/20141127132806/assets_manifest_backup )
DEBUG[435343cb]     ls: cannot access /home/deploy/project/releases/20141127132806/assets_manifest_backup
DEBUG[435343cb]     : No such file or directory
INFO[8c33627a] Running ~/.rvm/bin/rvm 2.1.4@project_rails32 do bundle exec rake assets:precompile on ip
DEBUG[8c33627a] Command: cd /home/deploy/project/releases/20141127132806 && ( RAILS_ENV=production ~/.rvm/bin/rvm 2.1.4@project_rails32 do bundle exec rake assets:precompile )
```

**Comment by augustosamame** [comment]
For anybody stumbling over this thread because of the same error:

```
ls: cannot access /home/deploy/my_project/releases/20141209175003/assets_manifest_backup
No such file or directory

```
Sprockets 3.0 now saves the manifest as a hidden file in the public directory.

https://github.com/rails/sprockets/blob/v3.7.0/UPGRADING.md#publicassetsmanifest-abc123json-location

For example:

`.sprockets-manifest-d6920ff76e860c95236844566807d7b8.json`

so the proper command would be to copy this hidden file instead

EDIT: 

Actually, this commit:

https://github.com/capistrano-plugins/capistrano-faster-assets/commit/af3972964dcf1fe89de29b1298aa4f39532b9705

now handles the hidden file, so you can just ignore this error. The following line in the deploy log:

```
ls /home/deploy/rails_app/releases/20180707002604/public/assets/.sprockets-manifest*
/home/deploy/rails_app/releases/20180707002604/public/assets/.sprockets-manifest-d6920ff76e860c95236844566807d7b8.json
```

should have you covered.
